### ISSUE TITLE
Not filling whole timeslot expands event for another timeslot

### ISSUE THREAD

**Issue by KrallXZ** [jquense/react-big-calendar#1408]
#### Do you want to request a _feature_ or report a _bug_?
Report a bug
#### What's the current behavior?
![obraz](https://user-images.githubusercontent.com/6277709/62411208-06a89200-b5f0-11e9-9ddf-33d47f6336b7.png)
All of these events should start at 10:00, but the darkblue one is stretched for 1 whole timecell, so its height is now (1 timecell + expected height) and starts 1 timeslot before expecting start.
Green lasts for 1,5 timecell, darkblue for 2/3 timecell and lightblue for 1 timecell, so this happens only when not whole timecell is filled, but when It's at least 1 timecell it works like expected.

```jsx
<BigCalendar
            localizer={localizer}
            events={mappedEvents}
            defaultView={Views.DAY}
            step={30}
            timeslots={1}
            resources={mappedEmployees}
            defaultDate={moment(day).toDate()}
            views={[Views.DAY]}
            min={new Date(moment('5:30', 'H:mm'))}
            max={new Date(moment('19:00', 'H:mm'))}
            toolbar={false}
            onSelectEvent={handleEventSelection}
          />
```

#### What's the expected behavior?
They all should start at 10:00 and last for correct time.

**Comment by vAskitsa** [comment]
I recently update to rbc version 0.22.0 and struggle with same problems. My one timeslot is 30 minutes and step is 15 minutes. When i try to render events shorter than step i get problems. Any solutions?

![image](https://user-images.githubusercontent.com/44556897/62758929-7a331f00-ba88-11e9-8eb3-6146cec4de28.png)

**Comment by stianeikeland** [comment]
This is the same issue as: #1396
Seems like it was caused by a change added in #1381

**Comment by KrallXZ** [comment]
It looks like #1447 should fix it, but I still have same behavior like in first post.

![obraz](https://user-images.githubusercontent.com/6277709/65673612-6a2cca00-e04b-11e9-829b-e01dfd64d23b.png)

**Comment by milinpaul** [comment]
@KrallXZ How did you make different colors for different events with highlighted in the start. 
Appreciate you help.

**Comment by KhaledMohamedP** [comment]
@KrallXZ @v1k45 

can you check if this pending PR fixes your issue #1473 ? 

We are waiting for the maintainer to review and merge this PR soon 😄

**Comment by KrallXZ** [comment]
@KhaledMohamedP It's still the same.
![obraz](https://user-images.githubusercontent.com/6277709/68678113-9fd73500-055d-11ea-975f-2f50cfebebcf.png)

**Comment by vAskitsa** [comment]
Unfortunately rearrangement algorithm does not solve this pretty serious problem. Still same behavior.

**Comment by stianeikeland** [comment]
Still an issue, please don’t close dear stalebot

**Comment by vAskitsa** [comment]
Yes, still a big issue.
