### ISSUE TITLE
Drag event from outside having stuck preview state until other event is moved.

### ISSUE THREAD

**Issue by ReetiMauryaCrest** [jquense/react-big-calendar#2763]
I am trying to create a DragAndDrop calendar using this library and date-fns localization module inside MUI based project. I have made all the setting to setup and work with drag and drop calendar, everything is working fine except for a case where when I drag an event item from outside the calendar, it is stuck in its preview state even after I have dropped it inside the calendar.

This creates following issues in my calendar working:
- The event is shown like it is on 2 days instead of 1 day (so 10th and 11th July instead of just 11th) because preview state does not change time data to midnight while dragging across calendar.
- Even though this preview event internally has different timing, my main events state still maintains time in midnight (I don't know why but it is not applied to the calendar), thus when I move another event in calendar the preview automatically gets removed and it is replaced by actual event time (making it seem like it glitched and become shorter).
- This preview remain in the calendar until I don't move another event, so I can click on this and it works like other events. So anything I do on these preview works halfway through, like my remove event code removes data from events but the preview stays (and I can the remove code multiple times on the same preview as it does not move).

I have made a codesandbox showing this issue but I don't know why it keeps crashing: [https://codesandbox.io/p/sandbox/react-big-calendar-issue-4tsm2d](https://codesandbox.io/p/sandbox/react-big-calendar-issue-4tsm2d)

Here is my component for reference (sorry for the length, I have removed many things but it is still large example):

```
import { useState } from 'react';
import { Calendar, dateFnsLocalizer } from 'react-big-calendar';
import {format, parse, startOfWeek, getDay} from 'date-fns';
import enUS from 'date-fns/locale/en-US';
import withDragAndDrop from 'react-big-calendar/lib/addons/dragAndDrop';
import { Box, List, ListItem, Paper } from '@mui/material';

const localizer = dateFnsLocalizer({
    format,
    parse,
    startOfWeek,
    getDay,
    locales: { 'en-US': enUS },
});

const DnDCalendar = withDragAndDrop(Calendar);

const DraggableItem = ({ id, title, onDragStartItem }) => {
    const handleDragStart = (e) => {
        e.dataTransfer.setData('text/plain', JSON.stringify({ id, title }));
        onDragStartItem({ id, title });
    };

    return (
        <ListItem
            draggable
            onDragStart={handleDragStart}
            component={Paper}
            sx={{ mb: 1, cursor: 'grab' }}>
            {title}
        </ListItem>
    );
};

const Sidebar = ({ schedules, onDragStartItem }) => (
    <List>
        {schedules.map((s) => {
            return (
                <DraggableItem
                    key={s.id}
                    id={s.id}
                    title={s.title}
                    onDragStartItem={onDragStartItem}
                />
            );
        })}
    </List>
);

const ScheduleCalendar = () => {
    const [events, setEvents] = useState([]);
    const [dragged, setDragged] = useState(null);

    const [schedules, setSchedules] = useState(
        Array.from({ length: 5 }, (_, i) => ({
            id: `sched-${i + 1}`,
            title: `Schedule ${i + 1}`,
        }))
    );

    const handleEventDrop = ({ event, start, end, allDay }) => {
        setEvents((prev) =>
            prev.map((evt) =>
                evt.id === event.id ? { ...evt, start, end, allDay } : evt
            )
        );
    };

    const handleRightClick = (event) => {
        console.log('Right-clicked event:', event);
        console.log('Events data in handleRightClick', events);
    };

    return (
        <>
            <Box display="flex" height="100vh">
                <Box width={240} p={2} borderRight="1px solid #ccc">
                    <Sidebar
                        schedules={schedules}
                        onDragStartItem={setDragged}
                    />
                </Box>
                <Box flexGrow={1} p={2}>
                    <DnDCalendar
                        localizer={localizer}
                        events={events}
                        defaultView="month"
                        style={{ height: '100%' }}
                        components={{
                            event: (props) => (
                                <div
                                    onContextMenu={(e) => {
                                        e.preventDefault();
                                        handleRightClick(props.event);
                                    }}
                                    style={{
                                        width: '100%',
                                        height: '100%',
                                        padding: '4px',
                                        boxSizing: 'border-box',
                                        cursor: 'context-menu',
                                    }}>
                                    {props.title}
                                </div>
                            ),
                        }}
                        draggableAccessor={() => true}
                        onEventDrop={handleEventDrop}
                        dragFromOutsideItem={() =>
                            dragged
                                ? {
                                      title: dragged.title,
                                      allDay: false,
                                  }
                                : null
                        }
                        onDropFromOutside={({ start, end, allDay }) => {
                            if (!dragged) return;

                            console.log(
                                'onDropFromOutside',
                                start,
                                end,
                                allDay
                            );

                            setEvents((evs) => [
                                ...evs,
                                {
                                    id: `evt-${Date.now()}`,
                                    title: dragged.title,
                                    start,
                                    end,
                                    allDay,
                                },
                            ]);
                            setSchedules((prev) =>
                                prev.filter((sch) => sch.id !== dragged.id)
                            );
                            setDragged(null);
                        }}
                        selectable
                    />
                </Box>
            </Box>
        </>
    );
};

export default ScheduleCalendar;
```

**Comment by MohammadAbdulkader9** [comment]
add key property to your Calendar component, it will re-render the calendar and make sure the dropped item sits on its slot

**Comment by ReetiMauryaCrest** [comment]
@MohammadAbdulkader9  So are you saying it like 

```
<DnDCalendar
         key="my-calendar"
         ......
/>
```

and then change key after every calendar drop from outside calendar?

Edit: I tried this and as expected it works, but now it creates other problems like calendar view shifting to default view.

**Comment by MohammadAbdulkader9** [comment]
its was long time ago i used this way to go around this issue, but with the new release 1.19.4 this bug should be solved,

try

`key={events}`
-----
or create a custom view controller like below:

1.
// instead of "day" write you default view
`const [currentView, setCurrentView] = useState<"month" | "week" | "day" | "agenda" | "work_week">("day")
`
2.
 ```
const handleViewChange = useCallback(
            (view: "month" | "week" | "day" | "agenda" | "work_week") => {
                setCurrentView(view)
            },
            []
        )

```
3.
```
<DnDCalendar
...
view={currentView} 
onView={handleViewChange} 
views={["month", "week", "day", "agenda"]} // the view tabs that you want do display in the calendar
...
/>
```

read more:
https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--on-view

**Comment by ReetiMauryaCrest** [comment]
@MohammadAbdulkader9 I thought that changing calendar using key would cause other issues in system too (apart from obvious view switch) so I was avoiding implementing it, but after implementing your solution I have still not faced any issue, so I believe this solution works for me till this gets fixed in library. Thank you for recommending this.

**Comment by MohammadAbdulkader9** [comment]
you're welcome.

by using key it forces the Calendar state to re-render, when i was using the key property i didn't face any major issues, but i hope that the custom view controller fixes your issue temporarily.
